const vulgar = [
  // Vietnamese profanity and sexual terms.
  'địt',
  'địt mẹ',
  'địt con mẹ',
  'đụ',
  'đụ má',
  'đụ mẹ',
  'đéo',
  'đệch',
  'đệt',
  'đcm',
  'đm',
  'đmm',
  'dkm',
  'dm',
  'dmm',
  'vãi lồn',
  'vãi cặc',
  'vãi lìn',
  'vcl',
  'vl',
  'cặc',
  'con cặc',
  'cac',
  'cak',
  'buồi',
  'buoi',
  'lồn',
  'lon',
  'loz',
  'lìn',
  'mặt lồn',
  'cái lồn',
  'con mẹ mày',
  'thằng chó',
  'con chó',
  'óc chó',
  'đĩ',
  'điếm',
  'con đĩ',
  'con cave',
  'mất dạy',
  'chịch',
  'làm tình',
  'bú cu',
  'bú lồn',
  'liếm lồn',
  'xoạc',
  'nứng',
  'hiếp',

  // English profanity and sexual/adult terms.
  'fuck',
  'fucking',
  'fucker',
  'motherfucker',
  'shit',
  'bullshit',
  'bitch',
  'asshole',
  'dumbass',
  'bastard',
  'crap',
  'slut',
  'whore',
  'hoe',
  'cunt',
  'dick',
  'cock',
  'pussy',
  'balls',
  'boobs',
  'tits',
  'cum',
  'suck my',
  'blowjob',
  'handjob',
  'porn',
  'porno',
  'pornhub',
  'xxx',
  'nsfw',
  'nude',
  'nudes',
  'send nudes',
  'sexting',
  'sex',
  'have sex',
  'rape',
  'rapist',
  'molest',
  'hentai',
];

const privacy = [
  // Requests for personal information or private access.
  'address',
  'home address',
  'where do you live',
  'what is your address',
  'phone number',
  'mobile number',
  'give me your number',
  'send your number',
  'school name',
  'what school',
  'which school',
  'class name',
  'classroom',
  'teacher name',
  'real name',
  'full name',
  'your password',
  'send password',
  'share password',
  'login code',
  'verification code',
  'otp',
  'pin code',
  'exact location',
  'live location',
  'share location',
  'meet alone',
  'meet me',
  'come alone',
  'secret chat',
  'private photo',
  'private video',
  'hidden camera',
  'spy camera',
  'cctv',
  'surveillance',

  // Vietnamese privacy terms.
  'địa chỉ',
  'nhà ở đâu',
  'ở đâu',
  'số điện thoại',
  'số nhà',
  'tên trường',
  'trường nào',
  'lớp nào',
  'mật khẩu',
  'mã xác minh',
  'mã otp',
  'vị trí chính xác',
  'chia sẻ vị trí',
  'gặp riêng',
  'đi một mình',
  'ảnh riêng tư',
  'video riêng tư',
  'camera ẩn',
  'quay lén',
  'quay trộm',
  'camera giấu kín',
  'camera nhà nghỉ',
  'camera khách sạn',
  'quay phòng thay đồ',
];

const racist = [
  // Racial, ethnic, religious, and nationality-based hate terms.
  'nigger',
  'nigga',
  'chink',
  'gook',
  'spic',
  'wetback',
  'coon',
  'kike',
  'raghead',
  'camel jockey',
  'sand nigger',
  'white trash',
  'terrorist',
  'go back to your country',
  'deport you',
  'monkey',
  'ape',
  'dirty immigrant',
  'all muslims are terrorists',
  'all jews',
  'all black people',
  'all asian people',
];

const sexist = [
  // Gender, sexuality, body-shaming, and sexual harassment terms.
  'fag',
  'faggot',
  'dyke',
  'tranny',
  'shemale',
  'queer freak',
  'retard',
  'fat bitch',
  'ugly bitch',
  'stupid girl',
  'stupid woman',
  'manwhore',
  'gold digger',
  'incel',
  'virgin loser',
  'go make me a sandwich',
  'show me your body',
  'send body pic',
  'send sexy pic',
  'send bikini pic',
  'take off your clothes',
  'touch yourself',
  'are you a virgin',
  'pedophile',
  'pedo',
  'groomer',
  'child lover',
];

const suicide = [
  // English self-harm and suicide phrases.
  'kill myself',
  'kill yourself',
  'kys',
  'suicide',
  'commit suicide',
  'i want to die',
  'want to die',
  'end my life',
  'end your life',
  'cut myself',
  'cut yourself',
  'self harm',
  'self-harm',
  'suicidal',
  'suicidal thoughts',
  'overdose',
  'hang myself',
  'jump off a bridge',
  'jump off a building',

  // Vietnamese self-harm and suicide phrases.
  'tự tử',
  'tự sát',
  'muốn chết',
  'không muốn sống',
  'chán sống',
  'kết thúc cuộc đời',
  'cắt cổ tay',
  'tự làm đau',
  'tự hại',
  'uống thuốc tự tử',
  'treo cổ',
  'nhảy cầu',
  'nhảy lầu',
];

function unique(items) {
  return [...new Set(items.map((item) => String(item).toLowerCase().trim()).filter(Boolean))];
}

module.exports = {
  vulgar: unique(vulgar),
  privacy: unique(privacy),
  racist: unique(racist),
  sexist: unique(sexist),
  suicide: unique(suicide),
};
